name: cohere
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - hydra-core
  - pip
  - pip:
    - cohere
    - pinecone-client
    - spotipy
    - lyricsgenius
    - beautifulsoup4
    - umap
    - plotly-express
    - streamlit
